version: '3'
services:
  api:
    image: node:17-slim
    container_name: api
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm i && npm run dev"
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
